blog/MiniBlog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
]

blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'
urlpatterns = [
    path('',views.index,name='index'),
    path('contact/',views.contact,name='contact'),
    path('about/',views.about,name='about'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('login/',views.user_login,name='login'),
    path('logout/',views.user_logout,name='logout'),
    path('signup/',views.user_signup,name='signup'),
    path('addpost/',views.add_post,name='add_post'),
    path('updatepost/<int:id>',views.update_post,name='update_post'),
    path('deletepost/<int:id>',views.delete_post,name='delete_post'),
]

blog/models.py
from django.db import models
from django.utils import timezone
# Create your models here.
class Post(models.Model):
    title  = models.CharField(max_length=50)
    desc = models.TextField()
    posted_on = models.DateTimeField(default=timezone.now)

    
    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm,UsernameField
from django.contrib.auth.models import User
from django.utils.translation import gettext , gettext_lazy as _
from blog.models import Post

class SignUpForm(UserCreationForm):
    password1 = forms.CharField(label='Password' , widget=forms.PasswordInput(attrs = {'class': 'form-control'}))
    password2 = forms.CharField(label='Confirm Password' , widget=forms.PasswordInput(attrs = {'class': 'form-control'}))
    class Meta:
        model = User
        fields = ['username','email']
        labels = {'email': 'Email'}
        widgets = {'username':forms.TextInput(attrs = {'class':'form-control'}),
                   'email':forms.TextInput(attrs = {'class':'form-control'})
                   }
        
class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs = {'autofocus':True, 'class':'form-control'}))
    password = UsernameField(label= _('Password'), strip=False,
                              widget=forms.PasswordInput(attrs = {'autocomplete':'current-password',
                                                                   'class':'form-control'}
                                                        )
                            )
    
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title' , 'desc'] 
        labels = {'title': 'Title' ,'desc': 'Description'}
        widgets = {'title': forms.TextInput(attrs = {'class': 'form-control'}),
                   'desc': forms.Textarea(attrs = {'class': 'form-control'})}

blog/views.py
from django.shortcuts import render,HttpResponseRedirect,HttpResponse
from blog.forms import SignUpForm,LoginForm,PostForm
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import Group
from blog.models import Post
from django.urls import reverse
# Create your views here.
def index(request):
    posts = Post.objects.all()
    return render(request, 'blog/index.html',{'posts': posts})

def about(request):
    return render(request, 'blog/about.html')

def contact(request):
    return render(request, 'blog/contact.html')

def dashboard(request):
    if request.user.is_authenticated:
        posts  = Post.objects.all()
        user = request.user
        name = user.get_username()
        gps = user.groups.all()
        return render(request, 'blog/dashboard.html', {'posts': posts,'name':name,'groups': gps})
    else:
        return HttpResponseRedirect(reverse('blog:logout'))

def user_login(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form  = LoginForm(request = request , data = request.POST)
            if form.is_valid():
                uname = form.cleaned_data['username']
                pwd  = form.cleaned_data['password']
                user = authenticate(username = uname, password = pwd)
                if user is not None:
                    login(request, user)
                    messages.success(request,'User Logged-in Successfully!!!')
                    return HttpResponseRedirect('/dashboard/')
        else:
            form = LoginForm()
        return render(request,'blog/login.html',{'form':form})
    else:
        return HttpResponseRedirect('/dashboard/')

def user_logout(request):
    logout(request)
    messages.success(request,"User Logged-out Successfully!!!")
    return HttpResponseRedirect('/')

def user_signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            messages.success(request,"Congratulations!!! You are now an Author")
            user = form.save()
            group  = Group.objects.get(name = "Author")
            user.groups.add(group)
    else:
        form = SignUpForm()
    return render(request, 'blog/signup.html' ,{'form':form})

def add_post(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = PostForm(request.POST)
            if form.is_valid():
                title = form.cleaned_data['title']
                desc = form.cleaned_data['desc']
                pst  = Post(title=title, desc=desc)
                pst.save()
                messages.success(request,"Post Added Successfully!!!")
                return HttpResponseRedirect(reverse('blog:dashboard'))
        else:
            form = PostForm()
        return render(request, 'blog/addpost.html', {'form': form})
    else:
        return render(request, 'blog/login.html')
    
def update_post(request,id):
    if request.user.is_authenticated:
        if request.method == 'POST':
            obj = Post.objects.get(id=id)
            fm = PostForm(request.POST , instance=obj)
            if fm.is_valid():
                fm.save()
                messages.success(request,"Post Updated Successfully!!!")
                return HttpResponseRedirect(reverse('blog:dashboard'))
        else:
            obj = Post.objects.get(id = id)
            fm = PostForm(instance = obj)
        return render(request, 'blog/updatepost.html', {'fm':fm})
    else:
        return render(request, 'blog/login.html')
    
def delete_post(request,id):
    if request.user.is_authenticated:
        if request.method == 'POST':
            fm = Post.objects.get(id=id)
            fm.delete()
            messages.success(request,"Post Delete Successfully!!!")
            return HttpResponseRedirect(reverse('blog:dashboard'))
    else:
        return render(request, 'blog/login.html')
      
        

blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<div class="container mt-4 text-light">
    <h2 class="mb-4">About Page</h2>

    <div class="jumbotron bg-dark">
        <h1 class="display-4 font-weight-bold">MiniBlog Web App</h1>
        <p class="lead my-4">Welcome to the MiniBlog Web App, a simple yet powerful platform for sharing your thoughts and ideas through blog posts.</p>
        <hr class="my-2 bg-light">
        <p class="my-4">Whether you're a passionate writer or someone looking to express themselves, MiniBlog provides a user-friendly interface to create and publish your blogs.</p>
        <p class="my-4">Explore the features, connect with like-minded individuals, and make your mark in the digital world.</p>
    </div>

</div>
{% endblock %}

blog/templates/blog/addpost.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-3">Add New Post</h3>
    <form action="" method="post" >
        {% csrf_token %}
        {{ form.as_p}}
        <input type="submit" value="Add Post" class="btn btn-success my-1">
        <a href="{% url 'blog:dashboard' %}" class="btn btn-danger d-inline">Cancel</a>
    </form> 
</div>
{% endblock content %}

blog/templates/blog/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog Web-App</title>
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
</head>
<body>
    {% block my_content %}
    {% endblock %}
    
    <div class = "container-fluid-bg-dark">
        {% include 'blog/navbar.html' %}
    </div>

    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                {% block msg %}
                {% endblock msg %}
            </div>
        </div>
        <div class="row">
            {% block side %}
            {% endblock side %}


            {% block content %}
            {% endblock content %}
        </div>
    </div>

    <script src="{% static 'blog/js/bootstrap.js' %}"></script>
    <script src="{% static 'blog/js/jquery.js' %}"></script>
    <script src="{% static 'blog/js/popper.js' %}"></script>
</body>
</html>

blog/templates/blog/contact.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<div class="container mt-4 text-light">
    <h2 class="mb-4">Contact Page</h2>

    <form>
        <div class="form-group row">
            <label for="inputName" class="col-sm-2 col-form-label">Name</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="inputName" placeholder="Your Name">
            </div>
        </div>

        <div class="form-group row">
            <label for="inputEmail" class="col-sm-2 col-form-label">Email</label>
            <div class="col-sm-10">
                <input type="email" class="form-control" id="inputEmail" placeholder="Your Email">
            </div>
        </div>

        <div class="form-group row">
            <label for="inputMessage" class="col-sm-2 col-form-label">Message</label>
            <div class="col-sm-10">
                <textarea class="form-control" id="inputMessage" rows="5" placeholder="Your Message"></textarea>
            </div>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

blog/templates/blog/dashboard.html
{% extends 'blog/base.html' %}
{% load static %}
{% block msg %}
<div class="col-sm-3 text-white my-3">
    <h5 class="my-3">Profile: {{ name }}</h5>
    {% for group in groups %}
        <p>{{ group.name }}</p>
    {% endfor %}
</div>
{% if messages %}
    <div class="col-sm-9 my-3">
        {% for message in messages %}
        <div {% if message.tags %} class="alert alert-{{ message.tags }} alert-dismissible fade show" {% endif %}>
            <strong>{{ message }}</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
    </div>
{% endif %}
{% endblock msg %}

{% block side %}

{% endblock side %}

{% block content %}
<div class="col-sm-9 text-center">
    <h3 class="text-white my-3">Dashboard Page</h3>
    <h4 class="alert alert-info mt-3">Show Post Info</h4>

    {% if posts %}
    <table class="table table-hover bg-white">
        <thead>
            <tr class="text-center">
                <th scope="col" style="width: 5%">#</th>
                <th scope="col" style="width: 25%">Title</th>
                <th scope="col" style="width: 50%">Description</th>
                <th scope="col" style="width: 20%">Action</th>
            </tr>
        </thead>
        <tbody>
            {% for post in posts %}
            <tr>
                <th>{{ forloop.counter }}</th>
                <td>{{ post.title }}</td>
                <td>{{ post.desc }}</td>
                <td class="align-content-center">
                    <a href="{% url 'blog:update_post' post.id %}" class="btn btn-success btn-sm">Edit</a>
                    {% if perms.blog.delete_post %}
                    <form action="{% url 'blog:delete_post' post.id %}" method="post" class="d-inline">
                        {% csrf_token %}
                        <input type="submit" class="btn btn-danger btn-sm" value="Delete">
                    </form>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <div class="alert alert-warning mt-3" role="alert">
        No posts available.
    </div>
    {% endif %}

    <div class="text-left">
        <a href="{% url 'blog:add_post' %}" class="btn btn-success my-0">Add Post</a>
    </div>
</div>
{% endblock content %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<div class="container mt-4 text-light">
    <h2 class="mb-4">Welcome to the Index Page</h2>

    {% if messages %}
        {% for message in messages %}
            <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %} mb-4" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    {% for post in posts %}
        <div class="card mb-4 bg-dark text-light">
            <div class="card-body">
                <h1 class="card-title display-4 font-weight-bold">{{ post.title }}</h1>
                <p class="card-text lead">{{ post.desc }}</p>
            </div>
            <div class="card-footer bg-dark">
                <small class="text-muted">Posted on {{ post.posted_on }}</small>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}

blog/templates/blog/login.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-3">Login Page</h3>
    <form action="" method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group my-3">
                {{ field.label_tag }}
                {{ field }}
                <div class="text-warning">
                    {{ field.errors }}
                </div>
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary my-3">Login</button>
        {% if form.non_field_errors %}
            <div class="alert alert-danger my-3">
                {% for error in form.non_field_errors %}
                    {{ error }}
                {% endfor %}
            </div>
        {% endif %}
    </form>
</div>
{% endblock %}

blog/templates/blog/logout.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-3">Logout Page</h3>

</div>
{% endblock %}

blog/templates/blog/navbar.html
{% load static %}
{% block content %}
<div class="MyNav">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#" style="font-family:sans-serif; font-size: 2rem; color: #fdffff;">MiniBlog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item {% if request.path == '/' %}active{% endif %}">
                    <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:about' %}">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:contact' %}">Contact</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:dashboard' %}">Dashboard</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:signup' %}">Sign-up</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>
{% endblock %}

blog/templates/blog/signup.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-3">Be an Author:</h3>
    <hr>
    {% if messages %}
    {% for message in messages %}
    <p {% if message.tags %} class="alert alert-{{ message.tags }} mb-5" {% endif %}>{{ message }}</p>
    {% endfor %}
    {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        {% for fm in form %}
            {{ fm.label_tag }}
            {{ fm }}
            <div class="form-group  text-warning" >
                {{ fm.errors }}
            </div>
        {% endfor %}
        <input type="submit" value="Sign Up" class="btn btn-primary my-3">
        {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
        <p class="alert alert-danger my-3">{{ error }}</p>
        {% endfor %}
        {% endif %}
    </form>
</div>
{% endblock %}

blog/templates/blog/updatepost.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-3">Update Your Post:</h3>
    <hr>
    {% if messages %}
    {% for message in messages %}
    <p {% if message.tags %} class="alert alert-{{ message.tags }} mb-5" {% endif %}>{{ message }}</p>
    {% endfor %}
    {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        {% for fm in fm %}
            {{ fm.label_tag }}
            {{ fm }}
            <div class="form-group  text-warning" >
                {{ fm.errors }}
            </div>
        {% endfor %}
        <input type="submit" value="Update" class="btn btn-success my-1">
        {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
        <p class="alert alert-danger my-3">{{ error }}</p>
        {% endfor %}
        {% endif %}
    </form>
</div>
{% endblock %}